# we use travis for testing our builds and pushing it to the aws hosting

# to provide super user level permission - and make sure that it has sudo
sudo: required

# services that must have to run our test scripts or run scripts
services:
  - docker
  
before-install:
  - docker build -t mrityunjay2docker/docker-react-app -f Dockerfile.dev .
  
script:
  - docker run -e CI=true mrityunjay2docker/docker-react-app npm run test -- --coverage
  
deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker-react-app"
  env: "Dockerreactapp-env"
  bucket_name: "elasticbeanstalk-us-east-2-202116681626"
  on:
    branch: master
  access_key_id: $ACCESS_KEY_ID
  secret_access_key: 
    secure: $SECRET_ACCESS_KEY